// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDREsMDfmhRy8bjXEf7A4I842yTWZMWfh0',
    appId: '1:565216609905:web:ac931eef40fd486b66bdd0',
    messagingSenderId: '565216609905',
    projectId: 'fitness-flutter-app-3251e',
    authDomain: 'fitness-flutter-app-3251e.firebaseapp.com',
    storageBucket: 'fitness-flutter-app-3251e.firebasestorage.app',
    measurementId: 'G-ZJE3W4X8RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTizNpNt_Lk76wtiRtS2okFxYnNh7Ow94',
    appId: '1:565216609905:android:5672d2d35363d6f866bdd0',
    messagingSenderId: '565216609905',
    projectId: 'fitness-flutter-app-3251e',
    storageBucket: 'fitness-flutter-app-3251e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7asqIgYSibTXbvkNjIZ4I8FLxHRSksUs',
    appId: '1:565216609905:ios:f7e722bc9557007e66bdd0',
    messagingSenderId: '565216609905',
    projectId: 'fitness-flutter-app-3251e',
    storageBucket: 'fitness-flutter-app-3251e.firebasestorage.app',
    iosBundleId: 'com.codeforany.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7asqIgYSibTXbvkNjIZ4I8FLxHRSksUs',
    appId: '1:565216609905:ios:f7e722bc9557007e66bdd0',
    messagingSenderId: '565216609905',
    projectId: 'fitness-flutter-app-3251e',
    storageBucket: 'fitness-flutter-app-3251e.firebasestorage.app',
    iosBundleId: 'com.codeforany.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDREsMDfmhRy8bjXEf7A4I842yTWZMWfh0',
    appId: '1:565216609905:web:91d16aa206f35c3066bdd0',
    messagingSenderId: '565216609905',
    projectId: 'fitness-flutter-app-3251e',
    authDomain: 'fitness-flutter-app-3251e.firebaseapp.com',
    storageBucket: 'fitness-flutter-app-3251e.firebasestorage.app',
    measurementId: 'G-PFGLKSB2ME',
  );
}
